### ISSUE TITLE
updateJetCollection AK8

### ISSUE THREAD

**Issue by AlionaD** [cms-jet/NanoAODJMAR#15]
https://github.com/cms-jet/NanoAODJMAR/blob/bede8ed60911be15808d82c44781d2338cb05306/python/addBTV.py#L34

Updated b tag discriminators are not stored for AK8 (fat jet) although the function calls the correct models. At the same time, it works perfectly well for AK4 and AK8 Sub jets.  

@alefisico 
@andrzejnovak

**Comment by andrzejnovak** [comment]
@alefisico It looks to me like the issue is with the naming again. Could you check the suffixes/prefixes?

**Comment by alefisico** [comment]
Hi @AlionaD 
I just clone the master branch, run the `nano106X_on_mini106X_2017_mc_NANO.py` file and looking at the output rootfile, specfically the `Jet_btagDeepB_b`, I see that the branch is filled:

![Screenshot from 2020-06-18 15-28-36](https://user-images.githubusercontent.com/6405405/85026046-7841ee00-b178-11ea-916f-6bc625671a1a.png)

Can you give some instructions on how to replicate the issue?

**Comment by AlionaD** [comment]
[AK4JetDeepCSV.pdf](https://github.com/cms-jet/NanoAODJMAR/files/4799132/AK4JetDeepCSV.pdf)
[AK8JetDeepCSV.pdf](https://github.com/cms-jet/NanoAODJMAR/files/4799133/AK8JetDeepCSV.pdf)
[SubJetDeepCSV.pdf](https://github.com/cms-jet/NanoAODJMAR/files/4799134/SubJetDeepCSV.pdf)

Hi @alefisico

Yep, it is filled. My problem is: it doesn't match DeepCSV from the b tag analyzer, even though they both call the same model now. After adding b tag discriminators to addBTV.py and them being recalculated, nanoAOD's DeepCSV variables started to match variables from BTA for AK4 jets and  Sub jets. But for AK8 jets they still don't match. 
So my thought was that AK8 b tag discriminators had not been recalculated. But it looks like it is not the case, because if one adds this b tag discriminators directly to nanoAOD, it won't change anything either. Probably, I should close this issue.
